#include <iostream>
#include <conio.h>
using namespace std;

 main ()
{

    char ch1[20],ch2[20],ch3[20],ch4[20];

    cout << "Enter the name of the 1st person:\t" << endl;

    cin >> ch1;

    cout << "Enter the name of the 2nd person:\t" << endl;

    cin >> ch2;

    cout << "Enter the name of the 3rd person:\t" << endl;

    cin >> ch3;

    cout << "Enter the name of the 4th person:\t" << endl;

    cin >> ch4;

    cout << "1st person is\t" << ch1 << endl;

    cout << "2nd person is\t" << ch2<< endl;

    cout << "3rd person is\t" << ch3 << endl;

    cout << "4th person is\t" << ch4 << endl;



    getch ();


}
